name: On Pull Request
on: 
  pull_request:
    branches:
      - main
      - dev
jobs:
  run-on-pr:
    runs-on: ubuntu-latest
    steps:
      - name: run job on push
        run: echo "job triggered due to push event"
      - name: job completed
        run: echo "job completed"
