name: On Push
on: 
# - push
 - workflow_dispatch
jobs:
  run-on-push:
    runs-on: ubuntu-latest
    steps:
      - name: run job on push
        run: echo "job triggered due to push event"
      - name: job completed
        run: echo "job completed"
